Docs theming
opendatacube/datacube-core pull request #1179
Opened 2021-08-16 10:17 UTC by rowanwins

### Reason for this pull request

...

### Proposed changes

- 
- 

 - [ ] Closes #xxxx
 - [ ] Tests added / passed
 - [ ] Fully documented, including `docs/about/whats_new.rst` for all changes

2021-10-27 22:22 UTC, BexDunn approved these changes
Looks awesome to me.

2021-10-27 23:48 UTC, omad requested changes
I love the restructuring and re-themeing you've done Rowan, thank you!

There are a couple of things I would like changed though:
- I don't agree with expanding the content across the full width of the screen, I think the theme default makes more sense. On a big screen it is far too spread out both for aesthetics and usability.
- The front page needs more content, it's too sparse and empty, and doesn't draw people in. As a stop gap, I've tried including the contents of the README from the top of the repo.
- The image links on the front page need improving. I do like their intent. I think we need 4 of them to match all the documentation chapters, they need alt texts, their text could be more concise and I think they can be a lot more attractive, I can have a go...

I've made some of these changes, just pushing and building in a separate fork.

2021-10-28 09:38 UTC, omad approved these changes

2021-10-28 09:40 UTC, omad commented
Actually, lets merge this, and I'll open a new PR tomorrow with the changes I've been making.

There were a lot of sphinx errors and warnings that I've been fixing one by one.

2021-10-28 09:40 UTC, merged