#1204 Add path to stack exchange and slack
opendatacube/datacube-core pull request #1205
Opened 2021-10-10 01:16 UTC by whatnick

### Reason for this pull request
Partial work towards #1204 

### Proposed changes
Doc lines in issue template.

2021-10-10 02:01 UTC, woodcockr approved these changes
LGTM

2021-10-10 03:38 UTC, robbibt approved these changes

2021-10-10 21:38 UTC, alexgleith requested changes
Slack URL should be different.

2021-10-10 21:38 UTC, alexgleith commented on .github/ISSUE_TEMPLATE.md
> +> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](https://join.slack.com/t/opendatacube/shared_invite/zt-d6hu7l35-CGDhSxiSmTwacKNuXWFUkg).
The slack link is not https... I should probably put cloudfront on it with a cert!

2021-10-10 21:38 UTC, alexgleith commented on .github/ISSUE_TEMPLATE.md
> +> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](https://join.slack.com/t/opendatacube/shared_invite/zt-d6hu7l35-CGDhSxiSmTwacKNuXWFUkg).
Oh, the slack link is http://slack.opendatacube.org too

2021-10-10 21:57 UTC, whatnick commented
The Slack inviter is pretty gatekeepery since it works only with GA and
CSIRO emails and fails silently with others. The link in this PR is the
Slack native inviter and more widely usable.

On Mon, Oct 11, 2021, 08:09 Alex Leith ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Slack URL should be different.
> ------------------------------
>
> In .github/ISSUE_TEMPLATE.md
> <https://github.com/opendatacube/datacube-core/pull/1205#discussion_r725702076>
> :
>
> > @@ -17,4 +17,6 @@
>
>
>  > **Note:** Stale issues will be automatically closed after a period of six months with no activity.
> -> To ensure critical issues are not closed, tag them with the Github `pinned` tag .
> +> To ensure critical issues are not closed, tag them with the Github `pinned` tag.
> +> If you are a community member and not a maintainer please escalate this issue to maintainers via
> +> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](https://join.slack.com/t/opendatacube/shared_invite/zt-d6hu7l35-CGDhSxiSmTwacKNuXWFUkg).
>
> The slack link is not https... I should probably put cloudfront on it with
> a cert!
> ------------------------------
>
> In .github/ISSUE_TEMPLATE.md
> <https://github.com/opendatacube/datacube-core/pull/1205#discussion_r725702149>
> :
>
> > @@ -17,4 +17,6 @@
>
>
>  > **Note:** Stale issues will be automatically closed after a period of six months with no activity.
> -> To ensure critical issues are not closed, tag them with the Github `pinned` tag .
> +> To ensure critical issues are not closed, tag them with the Github `pinned` tag.
> +> If you are a community member and not a maintainer please escalate this issue to maintainers via
> +> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](https://join.slack.com/t/opendatacube/shared_invite/zt-d6hu7l35-CGDhSxiSmTwacKNuXWFUkg).
>
> Oh, the slack link is http://slack.opendatacube.org too
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/opendatacube/datacube-core/pull/1205#pullrequestreview-775713403>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADX7BBIIXHATKGN7J6G2UDUGIBXNANCNFSM5FV4GSFQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-11 21:48 UTC, benjimin commented
_"If you are a community member and not a maintainer please escalate this issue to maintainers via GIS StackExchange or Slack"_

What about wording it as: "_This issue tracker is for fixes and improvements to the ODC core library. For support using ODC, consider asking a question on GIS StackExchange or the ODC Slack._"?

My thoughts:
* ODC questions on GIS stack exchange are very likely to be **closed and downvoted**, like [this one](https://gis.stackexchange.com/q/413614/59848) was yesterday.
* Github _should_ be the correct place for escalating something to the attention of the maintainers.
* The community is performing a service by reporting issues. If we communicate expectations that are unnecessarily onerous (or present an exclusionary vibe), issues regarding the project will go unreported.

2021-10-12 00:04 UTC, alexgleith commented
Nah, this works for everyone @whatnick: http://slack.opendatacube.org/

2022-02-16 23:59 UTC, alexgleith commented
Yo @whatnick can you please update the Slack joining link to `http://slack.opendatacube.org`. Then we can merge this!

2022-04-12 22:18 UTC, alexgleith commented on .github/ISSUE_TEMPLATE.md
> +> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](https://join.slack.com/t/opendatacube/shared_invite/zt-d6hu7l35-CGDhSxiSmTwacKNuXWFUkg).
```suggestion
> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](http://slack.opendatacube.org).
```

2022-04-12 22:19 UTC, alexgleith approved these changes

2022-04-29 01:14 UTC, merged