Expand extra dimension support
opendatacube/datacube-core pull request #1593
Opened 2024-06-03 23:44 UTC by Kirill888

### Reason for this pull request

Part of hyperspectral work.

Generalize extra dimension description in the measurement metadata dictionary to allow specifying order of the extra dimensions. Also adds `units` field when defining extra coordinates for extra dimensions.

### Proposed changes

instead of 
```yaml
extra_dim = b
```

do

```yaml
dims = [b, y, x]
```

which also enables `yxb` arrangement

```yaml
dims = [y, x, rgb]
```

 - [ ] Closes #xxxx
 - [ ] Tests added / passed
 - [ ] Fully documented, including `docs/about/whats_new.rst` for all changes

2024-06-04 06:55 UTC, Ariana-B requested changes
Apologies if this is just me not understanding how this works/the broader context of things, but this PR seems rather incomplete? I would have expected `dims` and `units` to be used or validated somewhere. I also wonder if there needs to be any added logic to handle when both `dims` and `extra_dims` are provided.

Missing documentation in `whats_new` and tests (if applicable).

2024-06-04 12:59 UTC, Kirill888 commented
@Ariana-B yes it is incomplete, hence no whats new. This is really to update schemas so that it's easier to index datasets that include that extra information even though one can't load data like that directly with `dc.load`, @SpacemanPaul was saying new release of 1.9 branch will be made soon, would be good to have updated schema in that release. Also I don't want to keep on rebasing, especially while still don't have consistent formatting.

2024-06-04 23:50 UTC, SpacemanPaul reviewed
Seems minimal and mostly straightforward.

What's the plan for "legacy" extra_dims style metadata?  Are we going to attempt to backwards compatibility or will we raise an error and direct to the new format?

Happy to merge more or less as is, but does need a whats_new entry.

2024-06-05 01:03 UTC, Kirill888 commented
> What's the plan for "legacy" extra_dims style metadata? Are we going to attempt to backwards compatibility or will we raise an error and direct to the new format?

normalize `extra_dim: b` into `dims: [y,x,b]` then proceed as usual, but I strongly doubt anyone is using `extra_dim` in the wild, it was kinda semi-finished and required special driver that was never part of datacube-core.

2024-06-05 01:41 UTC, SpacemanPaul approved these changes

2024-06-05 02:23 UTC, Ariana-B approved these changes

2024-06-05 04:02 UTC, merged