Add 'wrapdateline' to Geometry.to_crs
opendatacube/datacube-core pull request #168
Opened 2017-02-21 05:27 UTC by v0lat1le

Adding support for coordinate systems spanning dateline

2017-02-21 05:37 UTC, omad requested changes
Cool functionality!

Should have some docs before it lands.

2017-02-21 05:37 UTC, omad commented on datacube/utils/geometry.py
> +    def to_crs(self, crs, resolution=None, wrapdateline=False):
It'd be good to get some documentation here describing what this does.

Mention that it only makes sense for geographic (maybe even throw an exception if passing it for a non-geographic projection.) And I assume that it turns a Polygon into a MultiPolygon with a piece on each side...

2017-02-21 05:37 UTC, omad commented on tests/test_geometry.py
> +    # assert wrapped.type == 'MultiPolygon' TODO: implement CutGeometryOnDateLineAndAddToMulti equivalent
Are these asserts ready to be uncommented?

2017-02-21 05:47 UTC, v0lat1le commented on tests/test_geometry.py
> +    # assert wrapped.type == 'MultiPolygon' TODO: implement CutGeometryOnDateLineAndAddToMulti equivalent
Nope, and probably never will be. It's quite wild to implement.
Hopefully, the GDAL method will be accessible through python API one day.
I'll add more details as a comment there I guess

2017-02-22 02:23 UTC, omad approved these changes

2017-02-22 02:30 UTC, merged