Product definition for Sentinel 2 ARD granules
opendatacube/datacube-core pull request #342
Opened 2018-01-11 23:34 UTC by harshurampur

### New product definition for Sentinel 2 ARD data

2018-01-12 00:04 UTC, mpaget commented
I suggest we check with the @AMA-AC crew to clarify that this is compatible with their work on the UK-based S2 ARD definition. Such a check a doesn't have to be a blocker for reviewing this particular contribution, but its worth checking with others in the ODC community who are also working in this space. I'll forward the pull request email to them and perhaps they can have an input.

Is this S2 ARD definition built for the Aust Copernicus Data Hub version of S2 data? If so, and if these data differ from the UK-based version (AMA can tell us), then perhaps we need to be explicit about the source or relevance of this S2 ARD versus other variants.

2018-01-12 00:25 UTC, harshurampur commented
@ mpaget I will check with Simon Oliver whether this product definition is just built for Alpha2 or can be compatible with other variants.

2018-01-12 01:34 UTC, harshurampur commented
@mpaget I have changed the file name to be 'ga_ard.yaml'  as this is supported for just GA nbar, nbart and pq products and will not support the Aust Copernicus Data Hub version

2018-01-16 01:57 UTC, andrewdhicks requested changes

2018-01-16 01:57 UTC, andrewdhicks commented on docs/config_samples/dataset_types/ga_ard.yaml
> +- name: 't_contiguity'
How do the `t_` bands differ from the others?
They both have the same aliases, which could cause an issue if we use them for band lookup.

2018-01-16 01:57 UTC, andrewdhicks commented on docs/config_samples/dataset_types/ga_ard.yaml
> +  nodata: -999
The `uint16` datatype can't support signed values such as -999.

2018-01-16 01:57 UTC, andrewdhicks commented on docs/config_samples/dataset_types/ga_ard.yaml
> +    cfmask:
Should be `contiguity`?

2018-01-16 01:57 UTC, andrewdhicks commented on docs/config_samples/dataset_types/ga_ard.yaml
> +    cfmask:
Should be `contiguity`?

2018-01-16 01:57 UTC, andrewdhicks commented on docs/config_samples/dataset_types/ga_ard.yaml
> +    cfmask:
Should be `contiguity`?

2018-01-16 01:57 UTC, andrewdhicks commented on docs/config_samples/dataset_types/ga_ard.yaml
> +  spectral_definition:
Do 2A and 2B have different spectral response functions?

2018-01-17 02:59 UTC, harshurampur reviewed
Updates according to the comments above : 
1. File name changed to ga_s2_ard.yaml to keep it specific to GA NBAR NBART  products 
2. Updated t_ as prefix to NBART data aliases within ARD product 
3. Confirm S2A and S2B have differing spectral responses (spectral response is measured on instrument prior to launch)
4. Contiguity replaces FMask as noted
5. uint16 updated to int16

2018-01-17 02:59 UTC, harshurampur commented on docs/config_samples/dataset_types/ga_ard.yaml
> +  nodata: -999
Yeah that's right, should have been 0. This was written by Simon, I am adding to the repo on his behalf I will confirm about the changes again. 
Thanks Andrew

2018-01-17 02:59 UTC, harshurampur commented on docs/config_samples/dataset_types/ga_ard.yaml
> +- name: 't_contiguity'
It differs as with prefix t_ as  nbar_t specifications and without as nbar.

2018-01-17 03:23 UTC, andrewdhicks approved these changes

2018-01-22 02:27 UTC, merged