Loading data architecture docs fixes
opendatacube/datacube-core pull request #391
Opened 2018-03-15 06:17 UTC by omad

### Reason for this pull request
I didn't finish the job of incorporating @Kirill888's awesome documentation on the
data load process in Data Cube, and mangled the name to boot.

This PR finishes the job.

### Proposed changes
- Rename Virtual... -> Data Loading
- Copy edit the Data Loading documentation
- Add lots of cross references to python classes and methods
- Remove the now superfluous Data Load docs
- Add support for including MathJax equations in the docs

 - [x] Closes #388
 - ~[ ] Tests added / passed~

2018-03-15 06:40 UTC, Kirill888 requested changes
Thanks Damien, just a few minor things I noticed.

2018-03-15 06:40 UTC, Kirill888 commented on docs/architecture/data_load.rst
> -Base on the user query, look up the index to find a list of `dataset` objects.
`Based on`

2018-03-15 06:40 UTC, Kirill888 commented on docs/architecture/data_load.rst
> -        For each dataset in the final chunk​
I'm pretty sure it goes over bands first, hence the problems raised in this issue #383

2018-03-15 06:40 UTC, Kirill888 commented on docs/architecture/data_load.rst
> -that would return each portion of thedata as a computation graph.​
`thedata`

2018-03-15 06:40 UTC, Kirill888 commented on docs/architecture/data_load.rst
> -Typically an application will match the output grid to the input grid,
`,` -> `.`

2018-03-15 06:50 UTC, omad commented
Aaah, thanks for all the suggested changes on the file I deleted... :)

2018-03-15 06:52 UTC, Kirill888 commented
duh

2018-03-15 06:54 UTC, Kirill888 submitted a review, later dismissed

2018-03-15 07:52 UTC, andrewdhicks requested changes

2018-03-15 07:52 UTC, andrewdhicks commented on docs/about/release_process.rst
> -.. _PyPI: https://pypi.python.org/pypi
Keep these links, except for `MailChimp` and `Datacube Environment`

2018-03-15 23:44 UTC, andrewdhicks submitted a review, later dismissed

2018-03-19 00:19 UTC, omad commented
*bump*

2018-03-19 00:34 UTC, Kirill888 approved these changes
👍

2018-03-19 01:11 UTC, merged