[WIP] Allow indexing URIs
opendatacube/datacube-core pull request #607
Opened 2018-12-03 01:02 UTC by omad

### Reason for this pull request
Until now, the core datacube tools have only supported reading documents from local paths. This PR adds support for reading from HTTP/HTTPS/S3 as well.

### Proposed changes

- 
- 

 - [ ] Closes #xxxx
 - [x] Tests added / passed
 - [ ] Fully documented, including `docs/about/whats_new.rst` for all changes

2018-12-11 05:35 UTC, Kirill888 requested changes

2018-12-11 05:35 UTC, Kirill888 commented on datacube/api/core.py
> +def set_resampling_method(measurements, resampling=None):
Few concerns with this one:

1. sometimes copies other times returns reference
2. not clear from the name that this is not done by reference, and you have to use the output
3. why can't I set resampling to None exactly?

2018-12-11 05:35 UTC, Kirill888 commented on datacube/index/hl.py
> +    supplied document are identical to dB versions
`dB` vs `DB`

2018-12-11 05:35 UTC, Kirill888 commented on datacube/scripts/product.py
> +    # def add_first_name(row):
delete?

2018-12-11 05:35 UTC, Kirill888 commented on datacube/ui/expression.py
> +This module exposes and single function :func:`parse_expression` which takes
`and` -> `a`

2018-12-12 00:07 UTC, uchchwhash commented on datacube/model/utils.py
> +from datacube.utils.py import sorted_items
is there a module named `py` or am I misreading this?

2018-12-12 00:09 UTC, uchchwhash commented on datacube/scripts/product.py
> +    # def add_first_name(row):
:+1:

2018-12-12 05:01 UTC, uchchwhash submitted a review, later dismissed
Looks really good, especially the `utils` re-org.

2018-12-13 00:02 UTC, uchchwhash approved these changes
Looks good to me! :+1:

2018-12-13 00:02 UTC, Kirill888 approved these changes
good purge, and utils was overdue for splitting.

2018-12-13 00:02 UTC, merged